### ISSUE TITLE
MixedReality.QR - Data property is empty 

### ISSUE THREAD

**Issue by BertrandOustriere** [chgatla-microsoft/QRTracking#6] opened 2019-12-18 19:21 UTC
Hello, 

I am using the Microsoft.MixedReality.QR NuGet package version **"0.5.2066-rc"** to track QRCodes on Hololens 2. Everything is working fine, excepted that the **unity editor crashes sometimes** with the following error : 

`Stack Trace of Crashed Thread 20032:
ERROR: SymGetSymFromAddr64, GetLastError: 'Le module spécifié est introuvable.' (Address: 00007FFABBA62BD0)
ERROR: SymGetModuleInfo64, GetLastError: 'Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.' (Address: 00007FFABBA62BD0)
0x00007FFABBA62BD0 ((<unknown>)) (function-name not available)
0x000001FC546E00F8 (mscorlib) System.Object.wrapper_native_00007FFABBA62BD0()
0x000001FC62ED5D39 (Microsoft.MixedReality.QR.DotNet) WinRT.ObjectReference``1.Finalize()
0x000001FC516894DC (mscorlib) System.Object.runtime_invoke_virtual_void__this__()
0x00007FFA62AB3479 (mono-2.0-bdwgc) mono_gc_reference_queue_new
0x00007FFA62AB20FE (mono-2.0-bdwgc) mono_callspec_parse
0x00007FFA62AB2365 (mono-2.0-bdwgc) mono_callspec_parse
0x00007FFA62A757E8 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFA62A75576 (mono-2.0-bdwgc) mono_threads_set_shutting_down
0x00007FFAD9EF7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFADBD8CED1 (ntdll) RtlUserThreadStart`

So I get the last version of the NuGet package **"0.5.2081"**. Now it seems there is no more crash, but the **Data property of the QRCodes I read is empty**. The RawDataSize is 31 though, but if I try to convert the bytes array from RawData to a string, it just gives me ' '.

My technical environment : 
**Unity 2019.2.6f1
MRTK 2.1
HoloLens 2**

Sorry for posting it here, but I cannot find the right location to declare the issue.

**Comment by Bertrand75014** [comment] 2019-12-19 08:53
The issue is still here using the very last version of the NuGet package "0.5.2082"

**Comment by Bertrand75014** [comment] 2019-12-19 09:47
I just notice this error at the application start on the device : 

`Plugins: Failed to load 'Microsoft.MixedReality.QR' because one or more of its dependencies could not be loaded.`

Could it be because the Microsoft.VCRTForwarders.1040.1.0.4 package, which comes with MixedReality.QR, is declared as a dependency but only contains x64 and Editor DLLs ?

**Comment by TChag** [comment] 2020-01-07 17:34
Unity 2019.2.17f1
v0.5.2081

Also no data on QRCode..
@Bertrand75014 do you happen to have any more info? Thank you.

**Comment by Bertrand75014** [comment] 2020-01-08 10:59
Hello @TChag, 
I haven't more info, so I'm using "0.5.2066-rc" for now. It returns the right data, which is enough for my current needs. 
To avoid the the editor's crashes brought with this pre-release version, I'm just wrapping the QRCode related calls with `#if !UNITY_EDITOR`

**Comment by chgatla-microsoft** [comment] 2020-01-23 20:45
This is regression in the microsoft.mixedreality.qr plugin, it is fixed in the latest version and will be published in couple of days. The last known good version to not have this bug is 0.5.2069

**Closed** 2020-06-23 17:33 UTC
